package m3.billgenerator;

import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;

/**
 *
 * @author Dhruva Kumar
 */
public class BillGen extends javax.swing.JFrame {

    /**
     * Creates new form BillGen
     */
    public BillGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jhcp = new javax.swing.JTextField();
        jlbl_itm1 = new javax.swing.JLabel();
        jlblitm_2 = new javax.swing.JLabel();
        jlblitm_3 = new javax.swing.JLabel();
        jfries = new javax.swing.JTextField();
        jburger = new javax.swing.JTextField();
        jpizza = new javax.swing.JTextField();
        header_meals = new javax.swing.JLabel();
        jlblitm_4 = new javax.swing.JLabel();
        jlollipops = new javax.swing.JTextField();
        jlblitm_5 = new javax.swing.JLabel();
        jnoodles = new javax.swing.JTextField();
        jwings = new javax.swing.JTextField();
        jlblitm_6 = new javax.swing.JLabel();
        jlblitm_7 = new javax.swing.JLabel();
        jbucket = new javax.swing.JTextField();
        jlblitm_8 = new javax.swing.JLabel();
        j65 = new javax.swing.JTextField();
        jlblitm_9 = new javax.swing.JLabel();
        jlblitm_10 = new javax.swing.JLabel();
        jmomo = new javax.swing.JTextField();
        jlblitm_11 = new javax.swing.JLabel();
        jmajestic = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlblitm_22 = new javax.swing.JLabel();
        jlblitm_23 = new javax.swing.JLabel();
        jtxtcd = new javax.swing.JTextField();
        jtxtcmc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtreceipt = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jBtotal = new javax.swing.JButton();
        jBtreceipt = new javax.swing.JButton();
        jBtreset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jlblitm_16 = new javax.swing.JLabel();
        jtea = new javax.swing.JTextField();
        jcoffee = new javax.swing.JTextField();
        jspd = new javax.swing.JTextField();
        jlblitm_14 = new javax.swing.JLabel();
        jlblitm_13 = new javax.swing.JLabel();
        jlblitm_15 = new javax.swing.JLabel();
        jlblitm_12 = new javax.swing.JLabel();
        header_meals1 = new javax.swing.JLabel();
        jlbl_itm2 = new javax.swing.JLabel();
        jcider = new javax.swing.JTextField();
        jrdwine = new javax.swing.JTextField();
        jbeer = new javax.swing.JTextField();
        jlblitm_17 = new javax.swing.JLabel();
        jcocktails = new javax.swing.JTextField();
        jlblitm_18 = new javax.swing.JLabel();
        jmocktails = new javax.swing.JTextField();
        jlblitm_19 = new javax.swing.JLabel();
        jgin = new javax.swing.JTextField();
        jlblitm_20 = new javax.swing.JLabel();
        jmarg = new javax.swing.JTextField();
        jlblitm_21 = new javax.swing.JLabel();
        jwhisk = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlblTax = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("********** HOT ON WHEELS RESTAURANT **********");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1480, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jhcp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jhcp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jhcp.setText("0");

        jlbl_itm1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbl_itm1.setText("PIZZA");

        jlblitm_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_2.setText("BURGER");

        jlblitm_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_3.setText("FRENCH FRIES");

        jfries.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jfries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfries.setText("0");

        jburger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jburger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jburger.setText("0");
        jburger.setMaximumSize(new java.awt.Dimension(35, 40));

        jpizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jpizza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpizza.setText("0");

        header_meals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        header_meals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_meals.setText("MAIN COURSE");

        jlblitm_4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_4.setText("NOODLES");

        jlollipops.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlollipops.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlollipops.setText("0");

        jlblitm_5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_5.setText("CHICKEN LOLLIPOPS");

        jnoodles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jnoodles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnoodles.setText("0");

        jwings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jwings.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwings.setText("0");

        jlblitm_6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_6.setText("CHICKEN WINGS");

        jlblitm_7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_7.setText("CHICKEN BUCKET (8PCS)");

        jbucket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbucket.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbucket.setText("0");

        jlblitm_8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_8.setText("PANEER 65");

        j65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        j65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j65.setText("0");

        jlblitm_9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_9.setText("HONEY CHILLI PANEER");

        jlblitm_10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_10.setText("CHICKEN MOMO");

        jmomo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmomo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmomo.setText("0");

        jlblitm_11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_11.setText("CHICKEN MAJESTIC");

        jmajestic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmajestic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmajestic.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmajestic, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmomo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jhcp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_7, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbucket, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jwings, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblitm_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlollipops, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbl_itm1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblitm_2)
                            .addComponent(jlblitm_3)
                            .addComponent(jlblitm_4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jburger, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jnoodles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(header_meals, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_meals)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_itm1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblitm_2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_3)
                    .addComponent(jfries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_4)
                    .addComponent(jnoodles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_5)
                    .addComponent(jlollipops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jwings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblitm_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_7)
                    .addComponent(jbucket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_8)
                    .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_9)
                    .addComponent(jhcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_10)
                    .addComponent(jmomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_11)
                    .addComponent(jmajestic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 510, 480));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jlblitm_22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblitm_22.setText("COST OF DRINKS ");

        jlblitm_23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblitm_23.setText("COST OF MAIN COURSE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblitm_22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblitm_23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtcmc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_22)
                    .addComponent(jtxtcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_23)
                    .addComponent(jtxtcmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 510, 130));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jtxtreceipt.setColumns(20);
        jtxtreceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtreceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtreceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 460, 700));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jBtotal.setBackground(new java.awt.Color(0, 0, 0));
        jBtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtotal.setForeground(new java.awt.Color(255, 255, 255));
        jBtotal.setText("TOTAL");
        jBtotal.setToolTipText("");
        jBtotal.setBorder(null);
        jBtotal.setMaximumSize(new java.awt.Dimension(47, 27));
        jBtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtotalActionPerformed(evt);
            }
        });

        jBtreceipt.setBackground(new java.awt.Color(0, 0, 0));
        jBtreceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtreceipt.setForeground(new java.awt.Color(255, 255, 255));
        jBtreceipt.setText("RECEIPT");
        jBtreceipt.setToolTipText("");
        jBtreceipt.setBorder(null);
        jBtreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtreceiptActionPerformed(evt);
            }
        });

        jBtreset.setBackground(new java.awt.Color(0, 0, 0));
        jBtreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtreset.setForeground(new java.awt.Color(255, 255, 255));
        jBtreset.setText("RESET");
        jBtreset.setToolTipText("");
        jBtreset.setBorder(null);
        jBtreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtresetActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXIT");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(jBtreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jBtreset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jBtreset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtreceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 1010, 70));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jlblitm_16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_16.setText("CIDER");

        jtea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtea.setText("0");

        jcoffee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcoffee.setText("0");
        jcoffee.setMaximumSize(new java.awt.Dimension(35, 40));

        jspd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jspd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jspd.setText("0");

        jlblitm_14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_14.setText("BEER");

        jlblitm_13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_13.setText("SPARKLING DRINKS");

        jlblitm_15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_15.setText("RED WINE");

        jlblitm_12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_12.setText("COFFEE");

        header_meals1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        header_meals1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_meals1.setText("DRINKS");

        jlbl_itm2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbl_itm2.setText("TEA");

        jcider.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcider.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcider.setText("0");

        jrdwine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrdwine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jrdwine.setText("0");

        jbeer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbeer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbeer.setText("0");

        jlblitm_17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_17.setText("COCKTAILS");

        jcocktails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcocktails.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcocktails.setText("0");

        jlblitm_18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_18.setText("MOCKTAILS");

        jmocktails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmocktails.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmocktails.setText("0");

        jlblitm_19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_19.setText("GIN");

        jgin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jgin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jgin.setText("0");

        jlblitm_20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_20.setText("MARGERITA");

        jmarg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmarg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmarg.setText("0");

        jlblitm_21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblitm_21.setText("WHISKEY");

        jwhisk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jwhisk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwhisk.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(header_meals1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlbl_itm2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtea, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jwhisk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmarg, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jgin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmocktails, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcocktails, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcider, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblitm_15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrdwine, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblitm_14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblitm_13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblitm_12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jcoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbeer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_meals1)
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_itm2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblitm_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_13)
                    .addComponent(jspd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_14)
                    .addComponent(jbeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_15)
                    .addComponent(jrdwine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblitm_16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_17)
                    .addComponent(jcocktails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_18)
                    .addComponent(jmocktails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_19)
                    .addComponent(jgin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_20)
                    .addComponent(jmarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblitm_21)
                    .addComponent(jwhisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 490, 480));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 12));

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("TAX");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("TOTAL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 490, 130));

        pack();
    }// </editor-fold>                        

    private void jBtotalActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Maincourse itmcst = new Maincourse();
        
        double itax,itotal,isubt;
        
        itmcst.pizza = itmcst.ppizza * Double.parseDouble(jpizza.getText());
        itmcst.burger = itmcst.pburger * Double.parseDouble(jburger.getText());
        itmcst.ffries = itmcst.pffries * Double.parseDouble(jfries.getText());
        itmcst.noodles = itmcst.pnoodles * Double.parseDouble(jnoodles.getText());
        itmcst.chilops = itmcst.pchilops * Double.parseDouble(jlollipops.getText());
        itmcst.chiwgs = itmcst.pchiwgs * Double.parseDouble(jwings.getText());
        itmcst.chibct = itmcst.pchibct * Double.parseDouble(jbucket.getText());
        itmcst.paneer = itmcst.ppaneer * Double.parseDouble(j65.getText());
        itmcst.honeychi = itmcst.phoneychi * Double.parseDouble(jhcp.getText());
        itmcst.chimomo = itmcst.pchimomo * Double.parseDouble(jmomo.getText());
        itmcst.chimajest = itmcst.pchimajest * Double.parseDouble(jmajestic.getText());
        
        itmcst.tea = itmcst.ptea * Double.parseDouble(jtea.getText());
        itmcst.coffee = itmcst.pcoffee * Double.parseDouble(jcoffee.getText());
        itmcst.sparkDrink = itmcst.psparkDrink * Double.parseDouble(jspd.getText());
        itmcst.beer = itmcst.pbeer * Double.parseDouble(jbeer.getText());
        itmcst.rdwine = itmcst.prdwine * Double.parseDouble(jrdwine.getText());
        itmcst.cider = itmcst.pcider * Double.parseDouble(jcider.getText());
        itmcst.cocktails = itmcst.pcocktails * Double.parseDouble(jcocktails.getText());
        itmcst.mocktails = itmcst.pmocktails * Double.parseDouble(jmocktails.getText());
        itmcst.gin = itmcst.pgin * Double.parseDouble(jgin.getText());
        itmcst.margerita = itmcst.pmargerita * Double.parseDouble(jmarg.getText());
        itmcst.whiskey = itmcst.pwhiskey * Double.parseDouble(jwhisk.getText());
        
        isubt=itmcst.GetAmount();
        itax=itmcst.cFindTax(isubt);
        itotal= isubt+itax;
        
        
        String Tax = String.format("Rs%.2f", itax);
        jtxtTax.setText(Tax);
        
        String Total = String.format("Rs%.2f", itotal);
        jtxtTotal.setText(Total);
        
        String cstDrinks = String.format("Rs%.2f", itmcst.drink);
        jtxtcd.setText(cstDrinks);
        
        String cstMainCourse = String.format("Rs%.2f", itmcst.maincourse);
        jtxtcmc.setText(cstMainCourse);
        
        
        
        
        
        

        
    }                                       

    private void jBtreceiptActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        int ref = 1325 + (int)(Math.random()*4238);

        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd/MM/yyyy");
        tDate.format(timer.getTime());

        jtxtreceipt.append("""
                            *** HOT ON WHEELS RESTAURANT ***
                           
                           Reference Number :\t"""+ref+
            "\n===========================\n"+
            "Main Course : \t\t"+jtxtcmc.getText()+"\n\n"+
            "Drinks : \t\t"+jtxtcd.getText()+"\n\n"+
            "==========================="+"\n\n"+
            "Tax : \t\t"+jtxtTax.getText()+"\n\n"+
            "Total : \t\t"+jtxtTotal.getText()+"\n"+
            "==========================="+
            "\n Date :"+tDate.format(timer.getTime())+
            "\n Time :"+tTime.format(timer.getTime())+
            "\n\n\t ****** Thankyou ******");

    }                                          

    private void jBtresetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JTextField cleartext = null;
        for(Component c: jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext=(JTextField)c;
                cleartext.setText("0");
            }
        }

        for(Component c: jPanel6.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext=(JTextField)c;
                cleartext.setText("0");
            }
        }

        for(Component c: jPanel7.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext=(JTextField)c;
                cleartext.setText("");
            }
        }

        for(Component c: jPanel3.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext=(JTextField)c;
                cleartext.setText("");
            }
        }

        jtxtreceipt.setText(null);
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Maincourse iexit = new Maincourse();
        iexit.iexitsystem();

    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel header_meals;
    private javax.swing.JLabel header_meals1;
    private javax.swing.JTextField j65;
    private javax.swing.JButton jBtotal;
    private javax.swing.JButton jBtreceipt;
    private javax.swing.JButton jBtreset;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jbeer;
    private javax.swing.JTextField jbucket;
    private javax.swing.JTextField jburger;
    private javax.swing.JTextField jcider;
    private javax.swing.JTextField jcocktails;
    private javax.swing.JTextField jcoffee;
    private javax.swing.JTextField jfries;
    private javax.swing.JTextField jgin;
    private javax.swing.JTextField jhcp;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlbl_itm1;
    private javax.swing.JLabel jlbl_itm2;
    private javax.swing.JLabel jlblitm_10;
    private javax.swing.JLabel jlblitm_11;
    private javax.swing.JLabel jlblitm_12;
    private javax.swing.JLabel jlblitm_13;
    private javax.swing.JLabel jlblitm_14;
    private javax.swing.JLabel jlblitm_15;
    private javax.swing.JLabel jlblitm_16;
    private javax.swing.JLabel jlblitm_17;
    private javax.swing.JLabel jlblitm_18;
    private javax.swing.JLabel jlblitm_19;
    private javax.swing.JLabel jlblitm_2;
    private javax.swing.JLabel jlblitm_20;
    private javax.swing.JLabel jlblitm_21;
    private javax.swing.JLabel jlblitm_22;
    private javax.swing.JLabel jlblitm_23;
    private javax.swing.JLabel jlblitm_3;
    private javax.swing.JLabel jlblitm_4;
    private javax.swing.JLabel jlblitm_5;
    private javax.swing.JLabel jlblitm_6;
    private javax.swing.JLabel jlblitm_7;
    private javax.swing.JLabel jlblitm_8;
    private javax.swing.JLabel jlblitm_9;
    private javax.swing.JTextField jlollipops;
    private javax.swing.JTextField jmajestic;
    private javax.swing.JTextField jmarg;
    private javax.swing.JTextField jmocktails;
    private javax.swing.JTextField jmomo;
    private javax.swing.JTextField jnoodles;
    private javax.swing.JTextField jpizza;
    private javax.swing.JTextField jrdwine;
    private javax.swing.JTextField jspd;
    private javax.swing.JTextField jtea;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtcd;
    private javax.swing.JTextField jtxtcmc;
    private javax.swing.JTextArea jtxtreceipt;
    private javax.swing.JTextField jwhisk;
    private javax.swing.JTextField jwings;
    // End of variables declaration                   
}

